### ISSUE TITLE
incorrect diacritical placement in v 0.3 of the package

### ISSUE THREAD

**Issue by benbini** [lxyu/pinyin#8]
Version 0.3 is producing incorrect diacritical marks:
```py
In [3]: pinyin.get("绝")
Out[3]: 'júe'
```

This issue is caused by a problem in Line 41 of pinyin.py:
`pinyin = pinyin[:vowel] + tonemarks[tone] + pinyin[vowel:]`

Which if changed to the following:
`pinyin = pinyin[:vowel] + pinyin[vowel:vowel+1] + tonemarks[tone] + pinyin[vowel+1:]`

Produces correct output for more cases:
```py
In [2]: pinyin.get("绝")
Out[2]: 'jué'

In [3]: pinyin.get("小")
Out[3]: 'xiǎo'

In [4]: pinyin.get("许")
Out[4]: 'xǔ'
```
However this fails with words like 操 and 被, which places marks incorrectly on the second vowel.  So the maybe the following:
```py
        elif format == "diacritical":
            # Find first vowel -- we should put the diacritical mark
            # just after
            vowels = [x for x in pinyin if x in "aeiou"]
            vowel = pinyin.index(vowels[1]) if len(vowels) > 1 else pinyin.index(vowels[0])
            if vowels[0] in "aeo" and len(vowels) > 1:
                pinyin = pinyin[:vowel] + tonemarks[tone] + pinyin[vowel:]
            else:
                pinyin = pinyin[:vowel] + pinyin[vowel:vowel+1] + tonemarks[tone] + pinyin[vowel+1:]
```
Which produces the best-seeming output of all:
```py
In [16]: pinyin.get("他")
Out[16]: 'tā'

In [17]: pinyin.get("绝")
Out[17]: 'jué'

In [18]: pinyin.get("小")
Out[18]: 'xiǎo'

In [19]: pinyin.get("被")
Out[19]: 'bèi'
```

**Comment by lxyu** [comment]
Thank you very much for correcting this, and sorry for the long delay, I must have somehow missed the notification.
